app/views/client.py
from contextlib import redirect_stderr
from datetime import date, datetime
from pydoc import render_doc
from flask import jsonify

from flask import Blueprint, make_response, render_template, url_for, request, flash , Response
from flask import session
from itsdangerous import json

from sqlalchemy import true
from werkzeug.utils import redirect

bp = Blueprint('client', __name__, url_prefix='/client')

@bp.route('/', methods=('POST','GET'))
def main():
    return render_template('client.html')

app/views/road.py
from contextlib import redirect_stderr
from datetime import date, datetime
from pydoc import render_doc
from flask import jsonify

from flask import Blueprint, make_response, render_template, url_for, request, flash , Response
from flask import session
from itsdangerous import json

from sqlalchemy import true
from werkzeug.utils import redirect

from app.forms import AddressForm
from .function.map import get_location
bp = Blueprint('road', __name__, url_prefix='/road')

@bp.route('/', methods=('POST','GET'))
def road_input():
    form = AddressForm()
    if request.method == 'POST' and form.validate_on_submit():
        address_latlng = get_location(form.address.data)
        if not address_latlng:
            flash("주소를 다시 입력하세요.")
        else:
            lat, lng = address_latlng
            #return render_doc('road.html', form=form, lat=lat, lng=lng)
            return render_template('road2.html', form=form, lat=lat, lng=lng)

    return render_template('road.html', form=form)

@bp.route('/map')
def lat_lng_map():
    return jsonify(lat = request.args.get('lat', 123),
                   lng = request.args.get('lng', 30))

@bp.route('/map2')
def test():
    return render_template('inc/address_searchs.html')




def ymd(fmt):
    def trans(date_str):
        return datetime.strftime(date_str, fmt)
    return trans

@bp.route('/dt')
def dt():
    datestr = request.values.get('date', date.today(), type=ymd('%y-%m-%d'))
    return "우리나라 "+ str(datestr)


@bp.route('/wc')
def wc():
    key = request.args.get('key')
    val = request.args.get('val')
    res = Response("SET COOKIE")
    res.set_cookie(key, val)
    session['Token'] = '123x'
    return make_response(res)

app/views/service.py
from contextlib import redirect_stderr
from datetime import date, datetime
from pydoc import render_doc
from flask import jsonify

from flask import Blueprint, make_response, render_template, url_for, request, flash , Response
from flask import session
from itsdangerous import json

from sqlalchemy import true
from werkzeug.utils import redirect

bp = Blueprint('service', __name__, url_prefix='/service')

@bp.route('/', methods=('POST','GET'))
def main():
    return render_template('service.html')

app/views/teaminfo.py
from contextlib import redirect_stderr
from datetime import date, datetime
from pydoc import render_doc
from flask import jsonify

from flask import Blueprint, make_response, render_template, url_for, request, flash , Response
from flask import session
from itsdangerous import json

from sqlalchemy import true
from werkzeug.utils import redirect

bp = Blueprint('teaminfo', __name__, url_prefix='/teaminfo')

@bp.route('/', methods=('POST','GET'))
def main():
    return render_template('teaminfo.html')

app/templates/inc/address_searchs.html
<input type="text" id="sample2_postcode" placeholder="우편번호">
<input type="button" onclick="sample2_execDaumPostcode()" value="우편번호 찾기"><br>
<input type="text" id="sample2_address" placeholder="주소"><br>
<input type="text" id="sample2_detailAddress" placeholder="상세주소">
<input type="text" id="sample2_extraAddress" placeholder="참고항목">

<!-- iOS에서는 position:fixed 버그가 있음, 적용하는 사이트에 맞게 position:absolute 등을 이용하여 top,left값 조정 필요 -->
<div id="layer" style="display:none;position:fixed;overflow:hidden;z-index:1;-webkit-overflow-scrolling:touch;">
<img src="//t1.daumcdn.net/postcode/resource/images/close.png" id="btnCloseLayer" style="cursor:pointer;position:absolute;right:-3px;top:-3px;z-index:1" onclick="closeDaumPostcode()" alt="닫기 버튼">
</div>

<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
<script>
    // 우편번호 찾기 화면을 넣을 element
    var element_layer = document.getElementById('layer');

    function closeDaumPostcode() {
        // iframe을 넣은 element를 안보이게 한다.
        element_layer.style.display = 'none';
    }

    function sample2_execDaumPostcode() {
        new daum.Postcode({
            oncomplete: function(data) {
                // 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

                // 각 주소의 노출 규칙에 따라 주소를 조합한다.
                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                var addr = ''; // 주소 변수
                var extraAddr = ''; // 참고항목 변수

                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
                    addr = data.roadAddress;
                } else { // 사용자가 지번 주소를 선택했을 경우(J)
                    addr = data.jibunAddress;
                }

                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.
                if(data.userSelectedType === 'R'){
                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)
                    // 법정동의 경우 마지막 문자가 "동/로/가"로 끝난다.
                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){
                        extraAddr += data.bname;
                    }
                    // 건물명이 있고, 공동주택일 경우 추가한다.
                    if(data.buildingName !== '' && data.apartment === 'Y'){
                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                    }
                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.
                    if(extraAddr !== ''){
                        extraAddr = ' (' + extraAddr + ')';
                    }
                    // 조합된 참고항목을 해당 필드에 넣는다.
                    document.getElementById("sample2_extraAddress").value = extraAddr;
                
                } else {
                    document.getElementById("sample2_extraAddress").value = '';
                }

                // 우편번호와 주소 정보를 해당 필드에 넣는다.
                document.getElementById('sample2_postcode').value = data.zonecode;
                document.getElementById("sample2_address").value = addr;
                // 커서를 상세주소 필드로 이동한다.
                document.getElementById("sample2_detailAddress").focus();

                // iframe을 넣은 element를 안보이게 한다.
                // (autoClose:false 기능을 이용한다면, 아래 코드를 제거해야 화면에서 사라지지 않는다.)
                element_layer.style.display = 'none';
            },
            width : '100%',
            height : '100%',
            maxSuggestItems : 5
        }).embed(element_layer);

        // iframe을 넣은 element를 보이게 한다.
        element_layer.style.display = 'block';

        // iframe을 넣은 element의 위치를 화면의 가운데로 이동시킨다.
        initLayerPosition();
    }

    // 브라우저의 크기 변경에 따라 레이어를 가운데로 이동시키고자 하실때에는
    // resize이벤트나, orientationchange이벤트를 이용하여 값이 변경될때마다 아래 함수를 실행 시켜 주시거나,
    // 직접 element_layer의 top,left값을 수정해 주시면 됩니다.
    function initLayerPosition(){
        var width = 300; //우편번호서비스가 들어갈 element의 width
        var height = 400; //우편번호서비스가 들어갈 element의 height
        var borderWidth = 5; //샘플에서 사용하는 border의 두께

        // 위에서 선언한 값들을 실제 element에 넣는다.
        element_layer.style.width = width + 'px';
        element_layer.style.height = height + 'px';
        element_layer.style.border = borderWidth + 'px solid';
        // 실행되는 순간의 화면 너비와 높이 값을 가져와서 중앙에 뜰 수 있도록 위치를 계산한다.
        element_layer.style.left = (((window.innerWidth || document.documentElement.clientWidth) - width)/2 - borderWidth) + 'px';
        element_layer.style.top = (((window.innerHeight || document.documentElement.clientHeight) - height)/2 - borderWidth) + 'px';
    }
</script>

app/templates/inc/form_errors.html
<!-- field errors-->
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
</div>
{% endfor %}
<!--flash error-->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

app/templates/inc/form_roads.html
<div class="container my-3">
    <form id="road_form" method="post" class="post-form">
        {{ form.csrf_token }}
        {% include 'inc/form_errors.html' %}

        <div class="form-group">
            <label for="address">주소를 입력하세요</label>
            <input type="text" class="form-control" name="address" id="address" value="{{ form.address.data or '' }}" 
            data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo" onclick="hiddenTap()" readonly>
        </div>
       <button type="submit" class="btn btn-secondary" onclick="">확인</button>
    </form>
</div>

{% include 'inc/modals.html' %}


<div class="container my-3">
    <div></br></br></div>
    <div id='map' style='width:1000px;height:700px;display:inline-block;'></div>
</div>


<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
<script>
    function hiddenTap() {
      document.getElementById("hidden-address").style.display = "none";      
    }
        
</script>

app/templates/inc/modals.html
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">주소 선택</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form>
            <div class="form-group">
              <label for="recipient-name" class="col-form-label">주소</label>
              <input type="text" class="form-control" id="address-modal">
            </div>
            <form>
              <div class="form-group">
                <label for="recipient-name" class="col-form-label">상세 주소</label>
                <input type="text" class="form-control" id="address-detail-modal">
              </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary">선택</button>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
        </div>
      </div>
    </div>
  </div>

  <script>
    new daum.Postcode({
    onclose: function(state) {
        //state는 우편번호 찾기 화면이 어떻게 닫혔는지에 대한 상태 변수 이며, 상세 설명은 아래 목록에서 확인하실 수 있습니다.
        if(state === 'FORCE_CLOSE'){
            //사용자가 브라우저 닫기 버튼을 통해 팝업창을 닫았을 경우, 실행될 코드를 작성하는 부분입니다.

        } else if(state === 'COMPLETE_CLOSE'){
            //사용자가 검색결과를 선택하여 팝업창이 닫혔을 경우, 실행될 코드를 작성하는 부분입니다.
            //oncomplete 콜백 함수가 실행 완료된 후에 실행됩니다.
        }
    }
});

    var themeObj = {
      //bgColor: "", //바탕 배경색
      searchBgColor: "#0995C8", //검색창 배경색
      //contentBgColor: "", //본문 배경색(검색결과,결과없음,첫화면,검색서제스트)
      //pageBgColor: "", //페이지 배경색
      //textColor: "", //기본 글자색
      queryTextColor: "#FFFFFF" //검색창 글자색
      //postcodeTextColor: "", //우편번호 글자색
      //emphTextColor: "", //강조 글자색
      //outlineColor: "", //테두리
    };
  </script>
  

app/templates/inc/navbars.html
<!-- navigation bar-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">VISION</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('service.main') }}">&emsp;SERVICE&emsp;</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('road.road_input') }}">&emsp;SEARCH&emsp;</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">&emsp;BOARD&emsp;</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('client.main') }}">&emsp;CLINENT&emsp;</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link"  href="{{ url_for('teaminfo.main') }}">&emsp;TEAM INFO&emsp;</a>
            </li>
        </ul>
    </div>
</nav>